-- Insure360 AI – DDL Specification
-- Based on the supplied Insure360 AI data model.
-- Execute in a Snowflake environment with appropriate privileges.

CREATE DATABASE IF NOT EXISTS INSURE360_DB;

CREATE SCHEMA IF NOT EXISTS INSURE360_DB.RAW;
CREATE SCHEMA IF NOT EXISTS INSURE360_DB.AI;
CREATE SCHEMA IF NOT EXISTS INSURE360_DB.ANALYTICS;

-- =========================
-- RAW TABLES
-- =========================

CREATE OR REPLACE TABLE INSURE360_DB.RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR NOT NULL,
    CUSTOMER_NAME VARCHAR,
    AGE NUMBER,
    CITY VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    JOIN_DATE DATE,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE INSURE360_DB.RAW.POLICIES (
    POLICY_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    POLICY_TYPE VARCHAR,
    PREMIUM_AMOUNT NUMBER(12,2),
    START_DATE DATE,
    END_DATE DATE,
    POLICY_STATUS VARCHAR,
    CONSTRAINT PK_POLICIES PRIMARY KEY (POLICY_ID)
);

CREATE OR REPLACE TABLE INSURE360_DB.RAW.CLAIMS (
    CLAIM_ID VARCHAR NOT NULL,
    POLICY_ID VARCHAR,
    CUSTOMER_ID VARCHAR NOT NULL,
    CLAIM_DATE DATE,
    CLAIM_AMOUNT NUMBER(12,2),
    CLAIM_STATUS VARCHAR,
    CLAIM_REASON VARCHAR,
    CONSTRAINT PK_CLAIMS PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE INSURE360_DB.RAW.COMPLAINTS (
    COMPLAINT_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    COMPLAINT_DATE DATE,
    COMPLAINT_TYPE VARCHAR,
    COMPLAINT_STATUS VARCHAR,
    DESCRIPTION VARCHAR,
    CONSTRAINT PK_COMPLAINTS PRIMARY KEY (COMPLAINT_ID)
);

CREATE OR REPLACE TABLE INSURE360_DB.RAW.PAYMENTS (
    PAYMENT_ID VARCHAR NOT NULL,
    POLICY_ID VARCHAR,
    CUSTOMER_ID VARCHAR NOT NULL,
    DUE_DATE DATE,
    PAYMENT_DATE DATE,
    AMOUNT NUMBER(12,2),
    PAYMENT_STATUS VARCHAR,
    CONSTRAINT PK_PAYMENTS PRIMARY KEY (PAYMENT_ID)
);

CREATE OR REPLACE TABLE INSURE360_DB.RAW.INTERACTIONS (
    INTERACTION_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    INTERACTION_DATE TIMESTAMP,
    CHANNEL VARCHAR,
    TRANSCRIPT VARCHAR,
    AGENT_NAME VARCHAR,
    DURATION_MINUTES NUMBER,
    CONSTRAINT PK_INTERACTIONS PRIMARY KEY (INTERACTION_ID)
);

-- =========================
-- AI INTELLIGENCE
-- =========================

CREATE OR REPLACE TABLE INSURE360_DB.AI.INTERACTION_INSIGHTS (
    INTERACTION_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    SENTIMENT_SCORE NUMBER(10,4),
    SENTIMENT VARCHAR,
    AI_CLASSIFICATION VARCHAR,
    CANCELLATION_SIGNAL BOOLEAN,
    URGENCY VARCHAR,
    CONSTRAINT PK_INTERACTION_INSIGHTS PRIMARY KEY (INTERACTION_ID)
);

-- =========================
-- STRUCTURED CUSTOMER 360
-- =========================

CREATE OR REPLACE VIEW INSURE360_DB.ANALYTICS.VW_CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    COALESCE(p.TOTAL_PREMIUM, 0) AS TOTAL_PREMIUM,
    COALESCE(p.ACTIVE_POLICIES, 0) AS ACTIVE_POLICIES,
    COALESCE(cl.OPEN_CLAIMS, 0) AS OPEN_CLAIMS,
    COALESCE(co.OPEN_COMPLAINTS, 0) AS OPEN_COMPLAINTS,
    COALESCE(py.OVERDUE_PAYMENTS, 0) AS OVERDUE_PAYMENTS,
    p.DAYS_TO_RENEWAL
FROM INSURE360_DB.RAW.CUSTOMERS c
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        SUM(IFF(POLICY_STATUS = 'ACTIVE', PREMIUM_AMOUNT, 0)) AS TOTAL_PREMIUM,
        COUNT_IF(POLICY_STATUS = 'ACTIVE') AS ACTIVE_POLICIES,
        MIN(IFF(POLICY_STATUS = 'ACTIVE', DATEDIFF('day', CURRENT_DATE(), END_DATE), NULL)) AS DAYS_TO_RENEWAL
    FROM INSURE360_DB.RAW.POLICIES
    GROUP BY CUSTOMER_ID
) p ON c.CUSTOMER_ID = p.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT_IF(CLAIM_STATUS = 'OPEN') AS OPEN_CLAIMS
    FROM INSURE360_DB.RAW.CLAIMS
    GROUP BY CUSTOMER_ID
) cl ON c.CUSTOMER_ID = cl.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT_IF(COMPLAINT_STATUS IN ('OPEN','IN_PROGRESS')) AS OPEN_COMPLAINTS
    FROM INSURE360_DB.RAW.COMPLAINTS
    GROUP BY CUSTOMER_ID
) co ON c.CUSTOMER_ID = co.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT_IF(PAYMENT_STATUS = 'OVERDUE') AS OVERDUE_PAYMENTS
    FROM INSURE360_DB.RAW.PAYMENTS
    GROUP BY CUSTOMER_ID
) py ON c.CUSTOMER_ID = py.CUSTOMER_ID;

-- =========================
-- CUSTOMER INTELLIGENCE
-- =========================

CREATE OR REPLACE VIEW INSURE360_DB.ANALYTICS.VW_CUSTOMER_INTELLIGENCE AS
SELECT
    c360.*,
    COALESCE(i.NEGATIVE_INTERACTIONS, 0) AS NEGATIVE_INTERACTIONS,
    COALESCE(i.CANCELLATION_SIGNALS, 0) AS CANCELLATION_SIGNALS,
    COALESCE(i.HIGH_URGENCY_INTERACTIONS, 0) AS HIGH_URGENCY_INTERACTIONS
FROM INSURE360_DB.ANALYTICS.VW_CUSTOMER_360 c360
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT_IF(UPPER(SENTIMENT) = 'NEGATIVE') AS NEGATIVE_INTERACTIONS,
        COUNT_IF(CANCELLATION_SIGNAL = TRUE) AS CANCELLATION_SIGNALS,
        COUNT_IF(UPPER(URGENCY) = 'HIGH') AS HIGH_URGENCY_INTERACTIONS
    FROM INSURE360_DB.AI.INTERACTION_INSIGHTS
    GROUP BY CUSTOMER_ID
) i ON c360.CUSTOMER_ID = i.CUSTOMER_ID;

-- =========================
-- EXPLAINABLE RISK + NEXT BEST ACTION
-- =========================

CREATE OR REPLACE VIEW INSURE360_DB.ANALYTICS.VW_NEXT_BEST_ACTION AS
WITH scored AS (
    SELECT
        *,
        LEAST(
            100,
            (OPEN_CLAIMS * 15)
            + (OPEN_COMPLAINTS * 15)
            + (OVERDUE_PAYMENTS * 10)
            + (NEGATIVE_INTERACTIONS * 10)
            + (CANCELLATION_SIGNALS * 25)
            + (HIGH_URGENCY_INTERACTIONS * 10)
            + IFF(DAYS_TO_RENEWAL BETWEEN 0 AND 30, 10, 0)
        ) AS RISK_SCORE
    FROM INSURE360_DB.ANALYTICS.VW_CUSTOMER_INTELLIGENCE
),
classified AS (
    SELECT
        *,
        CASE
            WHEN RISK_SCORE >= 60 THEN 'HIGH'
            WHEN RISK_SCORE >= 30 THEN 'MEDIUM'
            ELSE 'LOW'
        END AS RISK_LEVEL,
        RTRIM(
            CONCAT(
                IFF(OPEN_CLAIMS > 0, 'Open claims; ', ''),
                IFF(OPEN_COMPLAINTS > 0, 'Open complaints; ', ''),
                IFF(OVERDUE_PAYMENTS > 0, 'Overdue payments; ', ''),
                IFF(NEGATIVE_INTERACTIONS > 0, 'Negative interactions; ', ''),
                IFF(CANCELLATION_SIGNALS > 0, 'Cancellation intent; ', ''),
                IFF(HIGH_URGENCY_INTERACTIONS > 0, 'High-urgency interactions; ', '')
            ),
            '; '
        ) AS RISK_REASON
    FROM scored
)
SELECT
    CUSTOMER_ID,
    RISK_SCORE,
    RISK_LEVEL,
    NULLIF(RISK_REASON, '') AS RISK_REASON,
    CASE
        WHEN CANCELLATION_SIGNALS > 0 AND OPEN_CLAIMS > 0 THEN 'CLAIM_ESCALATION'
        WHEN CANCELLATION_SIGNALS > 0 OR RISK_LEVEL = 'HIGH' THEN 'RETENTION_CALL'
        WHEN NEGATIVE_INTERACTIONS > 0 OR OPEN_COMPLAINTS > 0 THEN 'SERVICE_RECOVERY'
        WHEN OVERDUE_PAYMENTS > 0 THEN 'PAYMENT_REMINDER'
        WHEN DAYS_TO_RENEWAL BETWEEN 0 AND 30 THEN 'RENEWAL_OUTREACH'
        WHEN RISK_LEVEL = 'LOW' AND ACTIVE_POLICIES = 1 THEN 'CROSS_SELL'
        ELSE 'NO_IMMEDIATE_ACTION'
    END AS NEXT_BEST_ACTION,
    CASE
        WHEN CANCELLATION_SIGNALS > 0 AND OPEN_CLAIMS > 0 THEN 'Cancellation intent combined with unresolved claim.'
        WHEN CANCELLATION_SIGNALS > 0 OR RISK_LEVEL = 'HIGH' THEN 'Customer shows elevated retention/churn risk.'
        WHEN NEGATIVE_INTERACTIONS > 0 OR OPEN_COMPLAINTS > 0 THEN 'Negative service signals require recovery.'
        WHEN OVERDUE_PAYMENTS > 0 THEN 'Premium payment is overdue.'
        WHEN DAYS_TO_RENEWAL BETWEEN 0 AND 30 THEN 'Policy renewal is approaching.'
        WHEN RISK_LEVEL = 'LOW' AND ACTIVE_POLICIES = 1 THEN 'Healthy customer with opportunity for an additional product.'
        ELSE 'No immediate intervention required.'
    END AS ACTION_REASON
FROM classified;

-- =========================
-- CUSTOMER DECISION
-- =========================

CREATE OR REPLACE VIEW INSURE360_DB.ANALYTICS.VW_CUSTOMER_DECISIONS AS
SELECT
    i.CUSTOMER_ID,
    i.CUSTOMER_NAME,
    i.CUSTOMER_SEGMENT,
    i.TOTAL_PREMIUM,
    i.ACTIVE_POLICIES,
    i.OPEN_CLAIMS,
    i.OPEN_COMPLAINTS,
    i.OVERDUE_PAYMENTS,
    i.DAYS_TO_RENEWAL,
    i.NEGATIVE_INTERACTIONS,
    i.CANCELLATION_SIGNALS,
    i.HIGH_URGENCY_INTERACTIONS,
    n.RISK_SCORE,
    n.RISK_LEVEL,
    n.RISK_REASON,
    n.NEXT_BEST_ACTION,
    n.ACTION_REASON
FROM INSURE360_DB.ANALYTICS.VW_CUSTOMER_INTELLIGENCE i
JOIN INSURE360_DB.ANALYTICS.VW_NEXT_BEST_ACTION n
  ON i.CUSTOMER_ID = n.CUSTOMER_ID;

-- =========================
-- CORTEX ANALYST SOURCE
-- =========================

CREATE OR REPLACE VIEW INSURE360_DB.ANALYTICS.VW_CUSTOMER_SEMANTIC_SOURCE AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    RISK_SCORE,
    RISK_LEVEL,
    RISK_REASON,
    TOTAL_PREMIUM,
    OPEN_CLAIMS,
    OPEN_COMPLAINTS,
    OVERDUE_PAYMENTS,
    DAYS_TO_RENEWAL,
    ACTIVE_POLICIES,
    NEGATIVE_INTERACTIONS,
    CANCELLATION_SIGNALS,
    HIGH_URGENCY_INTERACTIONS,
    NEXT_BEST_ACTION,
    ACTION_REASON
FROM INSURE360_DB.ANALYTICS.VW_CUSTOMER_DECISIONS;

-- NOTE:
-- Create the Snowflake Semantic View and Cortex Agent using the
-- implementation instructions in 10_SEMANTIC_VIEWS.md and
-- 13_AGENT_ARCHITECTURE.md. Exact syntax can vary by enabled
-- Snowflake account features/version.
